services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    image: vnq88/teacher-ai-dashboard-frontend:1.0.0
